import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { GoodResults } from "../components/Goodresults";
import { BadResults } from "../components/Badresults";
import { trpc } from "../utils/trpc";
import React from "react";
import { number } from "zod";

const Home: NextPage = () => {
  const firstplayer = trpc.playerDB.getPlayer1.useQuery();
  return (
    <>
      <Head>
        <title>oddBall</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/bbfavicon.ico" />
      </Head>
      <div className=" items-start bg-gradient-to-b from-orange-500 to-orange-600">
        <p className="pl-4 pt-2 font-mona  text-2xl text-slate-900">oddBall</p>
      </div>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-100 to-slate-50">
        <div className="h-20 w-80 flex-auto rounded-lg bg-slate-50">
          {firstplayer.data?.name}
        </div>
        <div>{firstplayer.data?.pts}</div>
      </main>
    </>
  );
};

export default Home;
